version: '3'
services:
  server:
    build:
      context: ./server
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - app-network

  bot:
    build:
      context: ./bot
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
